version: 1.0.{build}
init:
  - git config --global core.autocrlf true
build_script:
  - ps: .\build.ps1
clone_depth: 1
test: off
deploy: off
branches:
  only:
    - master
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
matrix:
  fast_finish: true
os: Visual Studio 2017