language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
solution: FlashReflection.sln
script:
  - dotnet --info
  - dotnet restore
  - dotnet build -f netcoreapp2.0
  - dotnet xunit ".\test\FlashReflection.Test" -f netcoreapp2.0